### ISSUE TITLE
Provide a demo website

### ISSUE THREAD

**Issue by Thiousi** [getkirby-plugins/modules-plugin#1]
Hey great work guys !
It'd be awesome to have a demo repo somewhere that already includes one or two modules so we can fork it and spin it from there !
Can't wait to test it !

**Comment by lukasbestle** [comment]
That's a great idea, thank you. I will set up an example `site/modules` directory and push it to a branch on this repo.

**Comment by lukasbestle** [comment]
There's now a demo `site/modules` directory [on the demo branch](https://github.com/getkirby-plugins/modules-plugin/tree/demo).
