### ISSUE TITLE
Modules are empty inside the panel

### ISSUE THREAD

**Issue by jenstornell** [getkirby-plugins/modules-plugin#15]
When I revisited a module all of a sudden everything was gone:

![image](https://cloud.githubusercontent.com/assets/927011/22020485/d134471c-dcb8-11e6-8704-3c0585a245d7.png)

But when I look at the content file, everything is still there:

![image](https://cloud.githubusercontent.com/assets/927011/22020508/f439e00a-dcb8-11e6-8399-ca9ea39b49e3.png)

What is wrong?

**Comment by lukasbestle** [comment]
Have you verified that the field names match up? Maybe there's a typo in the field name? I don't think this is related to the plugin.

**Comment by jenstornell** [comment]
It's so easy to just put the blame on the plugin. You are correct. I was copy/paste the structure field blueprint syntax from the docs and at a later point of time I changed it. That lead to that old pages was suffering from inconsistant field names.
