### ISSUE TITLE
Display actual module title in panel

### ISSUE THREAD

**Issue by SirNovi** [getkirby-plugins/modules-plugin#19]
I think, the actually active module title should be displayed in the panel. Right now, on creation of a module, a txt file is created with a title and the name of the chosen template is stored there. This is used in the panel as well. 

Modules allow the changing of the template but on changing the template the items title is not changed, this is sub-optimal. I.e. I can create a module of the type 'slider' throw some images in and then decide, I rather want to use the 'gallery' template. I can quickly make the change – which is neat – but the item in the panel will still be called 'Slider'. 

So, I think it would be nice, if the active module type title could be displayed if the title is not part of the blueprint.

**Comment by medienbaecker** [comment]
This can be achieved with the following hook:

```
kirby()->hook('panel.page.update', function($page) {
  if (str::contains($page->intendedTemplate(), "module.") AND $page->title() != $page->blueprint()->title()) {
      $page->update(array(
        'title' => $page->blueprint()->title()
      ));
  }
});
```

But please keep in mind that this will also override the `title` when you have a `title` field in the module blueprint.

It may be better to solve this in the plugin core, though.

**Comment by lukaskleinschmidt** [comment]
Damn i was too slow @medienbaecker :wink:.

Though I don't think this should be solved in the core. If you actually use the `title` field in the frontend this could be unwanted.

**Comment by SirNovi** [comment]
@medienbaecker had an unfair advantage as I was discussing the issue with him prior to posting here

The hook is a good solution for me. A perfect solution for me would be a change to the extension that checks if 'title' is a field that's defined in the modules blueprint.

**Comment by medienbaecker** [comment]
I hoped something like the following would work, but somehow `$oldPage` is identical to `$page`. 🤔 

```
kirby()->hook('panel.page.update', function($page, $oldPage) {
  if (str::contains($page->intendedTemplate(), "module.") AND $oldPage->title() == $oldPage->blueprint()->title() AND $page->title() != $page->blueprint()->title()) {
    $page->update(array(
      'title' => $page->blueprint()->title()
    ));
  }
});
```

Ideally this would check if the previous `title` field was identical to the previous blueprint title and only then update the `title` field. Do you have any idea how to solve this @lukaskleinschmidt?

**Comment by lukaskleinschmidt** [comment]
You probably wont be able to get the correct blueprint because kirby determines the blueprint by the template. The template (or to more specific the file name) is changed before the hook is called so there is actually no way for kirby to determine the previous template or blueprint.

You could store the template in a hidden field and go on from there. But I'm not sure if it is worth the hassle. I would argue that you either use the title field in the frontend or not and implement the hook to update the title if it fits your module style.

**Comment by lukaskleinschmidt** [comment]
Just some further digging. The template is cached an should actually be available but the chache gets flushed before the `$page` object gets cloned. So kirby fetches the new template.

https://github.com/getkirby/panel/blob/master/app/src/panel/models/page.php#L554

**Comment by medienbaecker** [comment]
Thanks for your quick answer, Lukas! 👍 
I thought this would be a great possibility to create a hook that fits each approach, with a title or without a title.

I've added an issue to the panel repository: https://github.com/getkirby/panel/issues/1025

**Comment by lukasbestle** [comment]
I'm closing this issue as I think that this shouldn't be solved in the plugin core. If you disagree, feel free to reopen. :)
