### ISSUE TITLE
Showing fatal error for (non-existing) module URL

### ISSUE THREAD

**Issue by yoeran** [getkirby-plugins/modules-plugin#2]
First off all, great plugin! Great way to let my clients build their own layouts while still being able to control enough so they don't make some ugly content!

Running into an ugly error though.
Say I have a page at `/about` and a module underneath with the title `introduction`.
This will work fine in the *about* page template. But when I visit `/about/introduction` I get this fatal error in my browser:

```
Fatal error: Call to undefined method Kirby\Modules\Modules::uid() in /kirby_site/site/plugins/modules/etc/template.php on line 6
```

Shouldn't that URL show the error page instead? Or am I missing some essential configuration?

**Comment by l4ci** [comment]
Same error for me.

**Comment by lukasbestle** [comment]
Thank you for reporting.
This was a typo. I just fixed it and it should work now.

**Comment by yoeran** [comment]
Thanks for the fast response, works like a charm!
