### ISSUE TITLE
Cannot leave translations blank

### ISSUE THREAD

**Issue by acstll** [getkirby-plugins/modules-plugin#23]
In a website with 2 languages, when I'm editing a module, if I put content in a field in language A, the same content shows up in language B. Then…

If a change B to something else, it works as expected.
If I try to leave B blank, it automatically gets the content from A within saving.

I'm using the sortable module as well: https://github.com/lukaskleinschmidt/kirby-sortable/tree/master/fields/modules

How could this be fixed?

I'm willing to do a PR if needed. I just don't have a clue where the relevant code is :•)

**Comment by lukasbestle** [comment]
This is the normal content fallback in Kirby. Please note that while the values of language A are displayed in the Panel, they are not actually saved to the content file of language B, it's just a Panel thing.

The same fallback happens in your templates. If you don't want that (if you want to keep fields deliberately blank), see [this section in the docs](https://getkirby.com/docs/panel/blueprints/form-fields#optional-field-values-in-non-default-languages).
