### ISSUE TITLE
Start Template with prechoosed modules

### ISSUE THREAD

**Issue by janstieler** [getkirby-plugins/modules-plugin#25]
Hi,

is it possible to start a template with loaded modules?
So that for the user don't need to add modules first before he can add content.

Cheers

**Comment by lukasbestle** [comment]
Unfortunately I don't quite understand what you mean. Do you want to set the Panel up so that it automatically creates modules when a new page is created?

**Comment by janstieler** [comment]
yes you understand me right.
Okay, honestly I havn't thought on the subpage builder. I will try it with this.

Thanks.

**Comment by lukasbestle** [comment]
You are welcome.
