### ISSUE TITLE
Trouble installing the plugin ->  "Mising modulesfield"

### ISSUE THREAD

**Issue by elenaramirez** [getkirby-plugins/modules-plugin#27]
Hi!

Is this plugin still working with new versions of kirby? I've tried to install with the latest version (2.5.12) but i'm getting an error The field class is missing for: modulesfield. 

Maybe i'm forgetting something? Anybody can help me with this?

Thank you so much!

**Comment by lukasbestle** [comment]
This plugin does not provide a field. Maybe what you were using is the [Sortable field](https://github.com/lukaskleinschmidt/kirby-sortable).

**Comment by elenaramirez** [comment]
OMG, i mixed plugins without even realize it! So sorry to bother you Lukas, i close myself the issue and go away embarrassed 🦀🦀🦀

**Comment by lukasbestle** [comment]
No problem. :)
