### ISSUE TITLE
Must have the snippet a suffix with .html.php 

### ISSUE THREAD

**Issue by janstieler** [getkirby-plugins/modules-plugin#3]
Hi,
normally I name my snippets only with .php not with .html.php.
Ist it necessary to name the module snippets with .html.php or is it equal?

Cheers

**Comment by lukasbestle** [comment]
It is necessary for compatibility with the Patterns plugin. :)

**Comment by SirNovi** [comment]
Your answer lead me to believe that I could probably drop the html part if I don't care about the Patterns plugin. That's not the case, it is always needed.  

- Just to clarify, in case another Dufus like me makes wrong assumptions.

**Comment by lukasbestle** [comment]
Yes, that's true. It is always required to make sure that the Modules plugin is always compatible with the Patterns plugin. Also there might be other kinds of supported PHP files later.
