### ISSUE TITLE
Can’t get modules to output

### ISSUE THREAD

**Issue by iainmcampbell** [getkirby-plugins/modules-plugin#5]
I’m using the most recent versions of Kirby and this plugin (just started this project today), on PHP 5.5.27 on OS X.

I’ve put the plugin in `site/plugins`, and I’ve put the demo modules in `site/modules`.

I’ve set up `site/blueprints/default.yml` and `site/blueprints/modules.yml` as in the readme.

The default template (`site/templates/default.php`) looks like so:

```php
<?php $page->modules() ?>
```

I’ve created a page, with a modules folder, and a module inside:

```
/site/content/module-test
  default.txt
  /modules
    /module1
      module.text.txt
```
  
and the contents of `site/content/module-test/modules/module1/module.text.txt` are:

```
Title: Text module

----

Text: Hello World
```

and I get an empty page. not even the HTML from the text module template. When I `var_dump` the output of `$page->modules()` I get `null`.

Am I missing something here? There’s nothing in the readme about how to format the modules, so I went with Kirby standard. There are also no error message to work from.

I’d really love to get this plugin to work as modular layout is kind of the holy grail of CMS, and would make it possible for me to use Kirby for client work. any help would be greatly appreciated!

**Comment by dweidner** [comment]
I had the same issue,the first time I ised the plugin.  The module needs to be visible. Use the panel interface or prepend a number (e.g. `01`) to the name of your module directory (`content/module-test/modules/01-module1`). Does that fix your issue?

**Comment by lukasbestle** [comment]
Yes, that is correct. From the README:

> These module subpages can be reordered in the Panel like other pages. The order in the Panel defines the order on the page. They can also be set to "invisible", which hides them on the page as well, so they can be used as drafts within a page.

The reason for this behavior is that it would otherwise be impossible to order modules if invisible ones are used as well. Also it can be very useful to "hide" modules until they are ready.

---

Thanks for the feedback. I have updated the "Printing the modules in the template" section in the README with this information so that it should be more clear.

**Comment by iainmcampbell** [comment]
That did it, thanks Daniel, Lukas! 👍
