### ISSUE TITLE
Redirecting with custom status code

### ISSUE THREAD

**Issue by gearsdigital** [getkirby-plugins/modules-plugin#7]
Wouldn't it be nice to redirect with status code *Moved Permanently* if anyone want to access module subpage? Afaik default of `go()` is `302`. Maybe we can use a custom setting here `c::set('modules.status.code', 301);`? 

```php
<?php
// Redirect to the page where the module appears
go($page->page(), 301);
```

**Comment by lukasbestle** [comment]
HTTP 301 is quite dangerous. It gets cached everywhere and I already had a lot of situations (unrelated to the Modules plugin) where people asked me why something redirected even if they already removed the redirection again. 301 should only be used for redirections where you know that the old URL will *never ever* **ever** be relevant again IMO.

**Comment by gearsdigital** [comment]
Perfect. Thanks!
