### ISSUE TITLE
How to access a module from another page?

### ISSUE THREAD

**Issue by gearsdigital** [getkirby-plugins/modules-plugin#8]
What is the preferred way to to access a module from another page?

**For example:** There is a page *About us* where we've defined some modules. Now I want to access a specific module from *About us* on my _Homepage_ so that I simply don't not need to create duplicated content.

```php
page('about-us')->module('statement'); // does not work
page('about-us')->children()->module('statement'); // does not work
page('about-us')->modules(); // does work, but it obviously prints all modules
```

**Comment by lukasbestle** [comment]
That would be [`$page->moduleList()`](https://github.com/getkirby-plugins/modules-plugin#page-modulelist):

```
page('about-us')->moduleList()->find('statement');
```

**Comment by gearsdigital** [comment]
Thank you very much for your answer!

If I do `echo page('praxis/ueber-uns')->moduleList()->find('impressionen-aus-der-praxis');` I get only a string`praxis/ueber-uns/impressionen-aus-der-praxis`. Maybe I miss something?

**Comment by lukasbestle** [comment]
No, that gives you the module page of course, not the rendered module.

What you are trying to do is currently not possible, but I have noted this feature for the future.

**Comment by lukasbestle** [comment]
Temporary hack to use this right now anyway (untested):

```php
$module = page('praxis/ueber-uns')->moduleList()->find('impressionen-aus-der-praxis');
if($moduleObj = $module->module()) {
  $moduleName = $moduleObj->name();
  
  tpl::load($moduleObj->snippetFile(), compact('module', 'moduleName'));
}
```

**Comment by gearsdigital** [comment]
Sounds good! I think it could be a practical way to have sitewide components. Your example works. Just had to `echo` it… Thanks!

**Comment by lukasbestle** [comment]
You are right. I have corrected my example above to use the third param of tpl::load.

**Comment by gearsdigital** [comment]
👍 

I added your example as page method in your `modules.php`. Do you want me to provide a PR?

```php
// Register $page->module($module) method
$kirby->set('page::method', 'module', function ($page, $module = null) {
    if ($module) {
        $module = $page->moduleList()->find($module);
        if($moduleObj = $module->module()) {
            $moduleName = $moduleObj->name();
            tpl::load($moduleObj->snippetFile(), compact('module', 'moduleName'), false);
        }
    }
    return false;
});

**Comment by lukasbestle** [comment]
Thank you, but this would lead to duplicate code.

**Comment by lukasbestle** [comment]
There is now a new method [`$module->render($data, $return)`](https://github.com/getkirby-plugins/modules-plugin#printing-single-modules) that makes it possible to render single modules.
